-- Executar com usuario SYS, sem senha
GRANT SELECT ON DBA_ROLE_PRIVS TO MV2000;
GRANT SELECT ON DBA_SYS_PRIVS  TO MV2000;

-- Executar o script abaixo com algum usuário DBAMV
GRANT CREATE USER TO DBAMV, DBASGU WITH ADMIN OPTION;
GRANT ALTER USER TO DBAMV, DBASGU WITH ADMIN OPTION;
GRANT DROP ANY TRIGGER TO DBAMV,DBASGU WITH ADMIN OPTION;
GRANT CREATE ANY TRIGGER TO DBAMV,DBASGU WITH ADMIN OPTION;
GRANT CREATE ANY INDEX TO DBAMV,DBASGU WITH ADMIN OPTION;
GRANT DROP USER TO DBAMV,DBASGU WITH ADMIN OPTION;
GRANT MV2000 TO DBAMV,DBASGU WITH ADMIN OPTION;
GRANT CONNECT, RESOURCE TO DBAMV,DBASGU WITH ADMIN OPTION;
GRANT CREATE ANY TABLE TO DBAMV,DBASGU WITH ADMIN OPTION;
GRANT DROP ANY TABLE TO DBAMV,DBASGU WITH ADMIN OPTION;
GRANT SELECT ANY TABLE TO DBAMV,DBASGU WITH ADMIN OPTION;
GRANT INSERT ANY TABLE TO DBAMV,DBASGU  WITH ADMIN OPTION;
GRANT GRANT ANY OBJECT PRIVILEGE TO DBAMV,DBASGU  WITH ADMIN OPTION;
GRANT ALTER ANY TABLE TO DBAMV,DBASGU WITH ADMIN OPTION;
GRANT UNLIMITED TABLESPACE TO DBAMV,DBAPS,DBASGU,MVINTEGRA WITH ADMIN OPTION;

