SELECT 
    B.CD_ATENDIMENTO,
    E.CD_PRO_FAT,
    A.DT_ALTA,
    F.DS_PRO_FAT,
    A.CD_PACIENTE,
    D.NM_PACIENTE,
    E.DT_FECHAMENTO DT_PAGAMENTO,
    E.QT_LANCAMENTO,
    E.VL_UNITARIO,
    B.VL_PREVISTO     TOTAL_PAGO,
    NVL(B.VL_DESCONTO, 0) DESCONTO,
    E.CD_PRESTADOR,
    E.CD_CONVENIO,
    E.TP_PAGAMENTO,
    CASE
        WHEN E.TP_PAGAMENTO = 'P' THEN
            'Particular'
        WHEN E.TP_PAGAMENTO = 'F' THEN
            'Fornecedor'
        WHEN E.TP_PAGAMENTO = 'C' THEN
            'Convenio'
        ELSE
            'Não Identificado = '''
            || E.TP_PAGAMENTO || ''''
    END TIPO_PAGAMENTO,
    /* 
    EXCLUIDOS POR NAO ENCONTRAR RELACAO ENTRE AS TABELAS ENVOLVIDAS
    G.DS_RECCON_REC   FORMA_PAGAMENTO,
    G.NM_RESPONSAVEL,
    */
    C.NR_PARCELA      NUM_PARCELAS
FROM ATENDIME A
JOIN CON_REC B 
     ON B.CD_ATENDIMENTO = A.CD_ATENDIMENTO
JOIN ITCON_REC C 
     ON C.CD_CON_REC = B.CD_CON_REC
JOIN PACIENTE D
     ON D.CD_PACIENTE = A.CD_PACIENTE
JOIN ITREG_AMB E
     ON E.CD_ATENDIMENTO = A.CD_ATENDIMENTO
JOIN PRO_FAT F
     ON F.CD_PRO_FAT = E.CD_PRO_FAT
/*
EXCLUIDO POR NAO ENCONTRAR RELACAO ENTRE AS TABELAS ENVOLVIDAS
LEFT JOIN RECCON_REC G
     ON G.CD_ITCON_REC = C.CD_ITCON_REC
     AND G.CD_CON_REC_LOTE = B.CD_CON_REC
*/
WHERE A.CD_PACIENTE = 107172
      AND E.Sn_Pertence_Pacote = 'N'
ORDER BY
      A.CD_ATENDIMENTO
      , F.CD_PRO_FAT
