SELECT  /*+RULE*/
    A.CD_AGENDA_CENTRAL,
    B.CD_IT_AGENDA_CENTRAL,
    D.CD_MOVIMENTO_AGENDA_CENTRAL,
    TRUNC(A.DT_AGENDA) DATA_AGENDA,
    COALESCE(B.CD_PACIENTE, H.CD_PACIENTE) PRONTUARIO,
    F.NM_PACIENTE,
    E.DS_ITEM_AGENDAMENTO ITEM_AGENDADO,
    SUBSTR(F.DS_MOTIVO, 1, 50) OBSERVACAO,
    G.DS_MOT_CANC,
    B.CD_CONVENIO,
    TRUNC(COALESCE(B.DT_NASCIMENTO, H.DT_NASCIMENTO+1)) DT_NASC,
    COALESCE(B.NR_DDD_FONE, H.NR_DDD_FONE) || ' - ' || COALESCE(B.NR_FONE, H.NR_FONE) FONE_FIXO,
    COALESCE(B.NR_DDD_CELULAR, H.NR_DDD_CELULAR) || ' - ' || COALESCE(B.NR_CELULAR, H.NR_CELULAR) CELULAR
FROM AGENDA_CENTRAL A
JOIN IT_MOVIMENTO_AGENDA_CENTRAL D
     ON D.CD_AGENDA_CENTRAL = A.CD_AGENDA_CENTRAL
JOIN LOG_OPERA_AGENDA_CENTRAL F
     ON F.CD_AGENDA_CENTRAL = A.CD_AGENDA_CENTRAL
     AND F.CD_IT_MOVIMENTO_AGENDA_CENTRAL = D.CD_IT_MOVIMENTO_AGENDA_CENTRAL
JOIN ITEM_AGENDAMENTO E
     ON E.CD_ITEM_AGENDAMENTO = D.CD_ITEM_AGENDAMENTO
JOIN MOT_CANC G
     ON G.CD_MOT_CANC = F.CD_MOT_CANC
LEFT JOIN IT_AGENDA_CENTRAL B
     ON B.CD_AGENDA_CENTRAL = A.CD_AGENDA_CENTRAL
     AND B.CD_IT_AGENDA_CENTRAL = F.CD_IT_AGENDA_CENTRAL
     AND B.CD_ITEM_AGENDAMENTO = E.CD_ITEM_AGENDAMENTO
LEFT JOIN PACIENTE H
     ON H.CD_PACIENTE = F.CD_PACIENTE
WHERE 
     F.TP_OPERACAO IN ('C') AND
     TRUNC(A.DT_AGENDA) BETWEEN '01/jan/2018' AND '10/dec/2019'
     AND TRUNC(A.DT_AGENDA) >= SYSDATE - 30
ORDER BY 
     DATA_AGENDA
/*
(A) Agendamento
(T) Transferencia
(B) Bloqueio de Agenda
(D) Desbloqueio de agenda
(E) Exclusao de Agenda
(H) Exclusao de horario
(C) Cancelamento de Horario
(R) Reversao de Cancelamento de horario
(P) Alteracao de paciente agendado
(HD) Exclusao de horario por desistencia
(HA) Exclusao de horario por Alta
(HZ) Exclusao de horario por dispensa
(AA) Alteracao de Agendamento
(CF) Confirmacao de falta
(RP) Retirar presenca
(CP) Confirmacao de Presenca
(RF) Retirar falta
(CC) Confirmacao de contato
*/
