SELECT A.CD_ATENDIMENTO,
A.CD_MOV_INT,
A.DT_MOV_INT,
A.TP_MOV,
A.CD_LEITO_ANTERIOR,
A.CD_LEITO,

B.CD_PACIENTE,

C.NM_PACIENTE,
D.DS_RESUMO,
E.CD_UNID_INT,
E.DS_UNID_INT


FROM dbamv.mov_int A,
ATENDIME B,
PACIENTE C, 
DBAMV.LEITO D,
DBAMV.UNID_INT E

WHERE A.DT_MOV_INT between  to_date('01/08/2016', 'dd/mm/yyyy') and to_date('31/08/2016', 'dd/mm/yyyy')

AND  A.CD_ATENDIMENTO = B.CD_ATENDIMENTO
AND B.CD_PACIENTE = C.CD_PACIENTE
AND A.CD_LEITO = D.CD_LEITO
AND D.CD_UNID_INT = E.CD_UNID_INT

AND E.CD_UNID_INT = '26'

AND C.CD_PACIENTE = '147789'




