


SELECT A.CD_PED_RX,A.CD_ATENDIMENTO,A.CD_SET_EXA,A.DT_PEDIDO,A.NR_CONTROLE,A.CD_SETOR,

B.NM_SET_EXA,
C.CD_EXA_RX,
E.DS_EXA_RX

FROM DBAMV.PED_RX A,
DBAMV.SET_EXA B,
DBAMV.ITPED_RX C,
DBAMV.EXA_RX E

WHERE A.DT_PEDIDO between  to_date('16/08/2016', 'dd/mm/yyyy') and to_date('17/08/2016', 'dd/mm/yyyy') 
AND A.CD_SET_EXA = B.CD_SET_EXA
AND C.CD_PED_RX = A.CD_PED_RX
AND C.CD_EXA_RX = E.CD_EXA_RX






