select --*
       DBAMV.CIDADE.NM_CIDADE
       ,COUNT (DBAMV.CIDADE.CD_CIDADE) AS QTDE
              
FROM
      DBAMV.AVISO_CIRURGIA 
     ,DBAMV.CIRURGIA_AVISO
     ,DBAMV.CIRURGIA
     ,DBAMV.ESPECIALID_CIRURGIA
     ,DBAMV.PACIENTE
     ,DBAMV.CIDADE
     
WHERE 
     (DBAMV.AVISO_CIRURGIA.CD_AVISO_CIRURGIA = DBAMV.CIRURGIA_AVISO.CD_AVISO_CIRURGIA
      AND DBAMV.CIRURGIA_AVISO.CD_CIRURGIA   = DBAMV.CIRURGIA.CD_CIRURGIA
      AND DBAMV.CIRURGIA.CD_CIRURGIA         = DBAMV.ESPECIALID_CIRURGIA.CD_CIRURGIA
      AND DBAMV.AVISO_CIRURGIA.CD_PACIENTE   = DBAMV.PACIENTE.CD_PACIENTE
      AND DBAMV.PACIENTE.CD_CIDADE           = DBAMV.CIDADE.CD_CIDADE)
     AND DBAMV.AVISO_CIRURGIA.DT_REALIZACAO
       BETWEEN '01/11/2011' --Data início
       AND '29/02/2012'--Data Fim 
     AND DBAMV.AVISO_CIRURGIA.SN_CONFIRMADO = 'S'
     AND DBAMV.ESPECIALID_CIRURGIA.CD_ESPECIALID = 33
     
GROUP BY 
     DBAMV.CIDADE.NM_CIDADE
     ,DBAMV.CIDADE.CD_CIDADE 

ORDER BY 2 DESC
           

 
           
