SELECT  DBAMV.PRE_MED.DT_PRE_MED
        ,DBAMV.PRE_MED.HR_PRE_MED
       -- DBAMV.Servico.DS_SERVICO
        ,DBAMV.PRESTADOR.NM_PRESTADOR
        ,count (DBAMV.ATENDIME.CD_PRESTADOR ) as qtde

FROM DBAMV.ATENDIME,
    -- DBAMV.Servico, 
     --DBAMV.PACIENTE--,
     --DBAMV.CIDADE,
     --dbamv.laudo_aih,
     --DBAMV.espec_sus
     DBAMV.PRESTADOR 
     ,DBAMV.PRE_MED    
WHERE 
     --DBAMV.ATENDIME.CD_PACIENTE = DBAMV.PACIENTE.CD_PACIENTE AND
     DBAMV.PRE_MED.CD_ATENDIMENTO = DBAMV.ATENDIME.CD_ATENDIMENTO
  --  AND DBAMV.ATENDIME.CD_SERVICO = DBAMV.Servico.CD_SERVICO
 -- AND DBAMV.PACIENTE.CD_CIDADE   = DBAMV.CIDADE.CD_CIDADE
 -- AND DBAMV.ATENDIME.CD_ATENDIMENTO  = DBAMV.LAUDO_AIH.CD_ATENDIMENTO
  --AND dbamv.laudo_aih.cd_espec_sus   = DBAMV.espec_sus.CD_ESPEC_SUS
    AND DBAMV.PRE_MED.CD_PRESTADOR = DBAMV.PRESTADOR.CD_PRESTADOR
    AND DBAMV.PRE_MED.DT_PRE_MED  BETWEEN '10/04/2012' AND '12/04/2012'
    AND DBAMV.PRE_MED.CD_PRESTADOR in (97,127,103,102)
    

group by  
          DBAMV.PRE_MED.DT_PRE_MED,
          DBAMV.PRE_MED.HR_PRE_MED
          --dbamv.atendime.cd_servico,
          --DBAMV.Servico.DS_SERVICO,
          ,DBAMV.PRESTADOR.NM_PRESTADOR
          
ORDER BY 3, 1, 4 DESC


