--<DS_SCRIPT>
-- DESCRIÇÃO..: OP 18350
-- RESPONSAVEL: Paulo Calixto
-- DATA.......: 10/04/2014 15:30
-- VERSÃO PACOTE: SUS-3-7 / BUILD-273
-- APLICAÇÃO....: FFAS
--</DS_SCRIPT>
--<USUARIO=DBAMV>
--<FORCA_EXECUCAO=S>


DECLARE
  CURSOR cPESQUISA(pGRUPO IN VARCHAR2) IS
    SELECT count('X')
	  FROM Dbamv.GRUPO_HABILITACOES_SUS
	 WHERE CD_GRU_HABILITACAO = pGRUPO;

  nCONT           NUMBER;

BEGIN
  OPEN  cPESQUISA('3500');
  FETCH cPESQUISA INTO nCONT;
  CLOSE cPESQUISA;

  IF nCONT = 0 THEN

    INSERT INTO Dbamv.GRUPO_HABILITACOES_SUS( CD_GRU_HABILITACAO, DS_GRU_HABILITACAO )
					 VALUES( '3500', 'Atenção Especializada Eixo/Serviço de Referência Eixo');
  END IF;

  OPEN  cPESQUISA('3600');
  FETCH cPESQUISA INTO nCONT;
  CLOSE cPESQUISA;

  IF nCONT = 0 THEN
    INSERT INTO Dbamv.GRUPO_HABILITACOES_SUS( CD_GRU_HABILITACAO, DS_GRU_HABILITACAO )
					 VALUES( '3600', 'COLETA DE VESTIGIOS DE VIOLÊNCIA SEXUAL');
  END IF;

  OPEN  cPESQUISA('3700');
  FETCH cPESQUISA INTO nCONT;
  CLOSE cPESQUISA;

  IF nCONT = 0 THEN
    INSERT INTO Dbamv.GRUPO_HABILITACOES_SUS( CD_GRU_HABILITACAO, DS_GRU_HABILITACAO )
					 VALUES( '3700', '** GRUPO CRIADO AUTOMATICAMENTE PELA CARGA SIGTAP');
  END IF;
  COMMIT;

END;



