SELECT A.cd_laudo,
A.CD_ATENDIMENTO,
A.DT_EMISSAO,
D.NM_PACIENTE,
A.CD_PRESTADOR_SOL,
(SELECT B.NM_PRESTADOR FROM DBAMV.PRESTADOR B WHERE A.CD_PRESTADOR_SOL = B.CD_PRESTADOR) AS NM_PRESTADOR_SOL,
A.CD_PROCEDIMENTO,
A.CD_PRESTADOR,
B.NM_PRESTADOR,
F.DS_ESPECIALID,

A.CD_CID_PRINCIPAL

FROM dbamv.LAUDO_AIH A,
DBAMV.PRESTADOR B,
DBAMV.ATENDIME C,
DBAMV.PACIENTE D, 
DBAMV.ESP_MED E,
DBAMV.ESPECIALID F 


WHERE DT_EMISSAO between  to_date('01/01/2016', 'dd/mm/yyyy') and to_date('21/09/2016', 'dd/mm/yyyy')
AND  (A.CD_PRESTADOR= B.CD_PRESTADOR)
AND A.CD_ATENDIMENTO = C.CD_ATENDIMENTO
AND C.CD_PACIENTE = D.CD_PACIENTE
AND B.CD_PRESTADOR = E.CD_PRESTADOR
AND E.CD_ESPECIALID = F.CD_ESPECIALID


